name: Docker Image for build - manylinux_2_34
'on':
  workflow_dispatch: null
  schedule:
  - cron: 0 1 * * mon
jobs:
  clone-and-build:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            arch: x64
          - runs-on: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: .github/workflows/manylinux_2_34.Dockerfile
        push: true
        tags: ${{ format('ghcr.io/{0}/manylinux_2_34_{1}', github.repository, matrix.arch) }}
