name: Release - Homebrew macOS-arm64
on:
  workflow_dispatch: null
  push:
    tags:
    - v*
    - test-release-*
env:
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_FAIL_LOG_LINES: 99999
jobs:
  build:
    # This runs on x64.
    # To install arm brew packages as build deps. See https://github.com/orgs/Homebrew/discussions/2843. Basically:
    # 1. Install `brew` at a separate location, exported as `$BREW`. This ensures that it does not mess up with the host arch brew.
    # 2. Use `$BREW fetch --force --bottle-tag=arm64_big_sur` to download bottles of the target arch.
    # 3. Use `$BREW install` to install them.
    runs-on: macos-12
    steps:
    - name: Brew
      run: brew config
    - name: Brew x64
      run: arch --x86_64 brew config
    - name: Brew location
      run: which brew
    - name: Prepare homebrew for arm
      run:
       |
          mkdir arm-homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C arm-homebrew
          export BREW="$PWD/arm-homebrew/bin/brew"
          echo $BREW
          $BREW config
          echo "BREW=$BREW" >> "$GITHUB_ENV"
    - name: Install arm build dependencies - openssl and python
      run:
        |
          for dep in openssl@1.1 python@3.11; do
            downloaded=$("$BREW" fetch --force --bottle-tag=arm64_big_sur $dep | grep 'Downloaded to: ' | sed 's/Downloaded to: //')
            "$BREW" install "$downloaded"
          done
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Grant Access
      run: git config --global --add safe.directory "$PWD"
    - name: set-env SAPLING_VERSION
      shell: bash
      run: echo "SAPLING_VERSION=$(ci/tag-name.sh)" >> $GITHUB_ENV
    - name: Prepare build environment
      run: 'eden/scm/packaging/mac/prepare_environment.py \

        -t aarch64-apple-darwin \

        -r ${{ env.SAPLING_VERSION }} \

        -o $(brew tap-info homebrew/core | sed -n ''2p'' | awk ''{printf $1}'')/Formula/sapling.rb'
    - name: Install and build Sapling bottle
      run: brew install --build-bottle sapling
    - name: Create Sapling bottle
      run: brew bottle sapling
    - name: Rename bottle to some platform specific name
      run: mv sapling*monterey.bottle.tar.gz sapling_${{ env.SAPLING_VERSION }}.arm64_monterey.bottle.tar.gz
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos-homebrew-arm64-bottle
        path: sapling*monterey.bottle.tar.gz
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Grant Access
      run: git config --global --add safe.directory "$PWD"
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: macos-homebrew-arm64-bottle
    - name: Create pre-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: bash ci/retry.sh bash ci/create-release.sh $(ci/tag-name.sh)
    - name: Upload Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: bash ci/retry.sh gh release upload --clobber $(ci/tag-name.sh) sapling*monterey.bottle.tar.gz
