name: Release - Homebrew macOS-arm64
'on':
  workflow_dispatch: null
  push:
    tags:
    - v*
    - test-release-*
jobs:
  build:
    # This runs on x64.
    runs-on: macos-12
    steps:
    - name: Brew
      run: brew config
    - name: Brew x64
      run: arch --x86_64 brew config
    - name: Brew location
      run: which brew
    - name: Prepare homebrew for arm
      run:
       |
          mkdir arm-homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C arm-homebrew
          export BREW="$PWD/arm-homebrew/bin/brew"
          echo $BREW
          $BREW config
    - name: Install arm dependency - openssl
      run:
        |
          response=$($BREW fetch --force --bottle-tag=arm64_big_sur openssl@1.1 | grep "Downloaded to" | sed 's/Downloaded to//')
          echo res $response
          $BREW install $response
    - name: Install arm dependency - python
      run:
        |
          response=$($BREW fetch --force --bottle-tag=arm64_big_sur python@3.11 | grep "Downloaded to" | sed 's/Downloaded to//')
          echo res $response
          $BREW install $response
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Grant Access
      run: git config --global --add safe.directory "$PWD"
    - name: set-env SAPLING_VERSION
      shell: bash
      run: echo "SAPLING_VERSION=$(ci/tag-name.sh)" >> $GITHUB_ENV
    - name: Prepare build environment
      run: 'eden/scm/packaging/mac/prepare_environment.py \

        -t aarch64-apple-darwin \

        -r ${{ env.SAPLING_VERSION }} \

        -o $(brew tap-info homebrew/core | sed -n ''2p'' | awk ''{printf $1}'')/Formula/sapling.rb'
    - name: Install and build Sapling bottle
      run: brew install --build-bottle sapling
    - name: Create Sapling bottle
      run: brew bottle sapling
    - name: Rename bottle to some platform specific name
      run: mv sapling*monterey.bottle.tar.gz sapling_${{ env.SAPLING_VERSION }}.arm64_monterey.bottle.tar.gz
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos-homebrew-arm64-bottle
        path: sapling*monterey.bottle.tar.gz
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Grant Access
      run: git config --global --add safe.directory "$PWD"
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: macos-homebrew-arm64-bottle
    - name: Create pre-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: bash ci/retry.sh bash ci/create-release.sh $(ci/tag-name.sh)
    - name: Upload Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: bash ci/retry.sh gh release upload --clobber $(ci/tag-name.sh) sapling*monterey.bottle.tar.gz
